### ISSUE TITLE
No element must be annotated as optional and as required

### ISSUE THREAD

**Issue by DavidTen1** [lars-reimann/api-editor#749]
![Screenshot 2022-06-24 at 15-22-34 API Editor](https://user-images.githubusercontent.com/101743941/175544961-9b846ad4-3119-43bf-b41a-94b8571cc803.png)

You can give an optional and a required annotation to the same element (e.g. the parameters). This must, however, never be possible.
E.g. when you choose an optional annotation, it can not be required one, however.
Only one variant of them must  be chosen and the other variant must not exist.

**Comment by lars-reimann** [comment]
Currently such validation only happens when the user clicks on the button "Generate adapters".

![image](https://user-images.githubusercontent.com/2501322/175560233-b79971c9-5753-425c-a3c5-e28cf7ca8bc0.png)

It would be preferable if this validation happened instantly in the editor without having to click buttons.
